### ISSUE TITLE
 MessageDatabase_Impl does not exist

### ISSUE THREAD

**Issue by devedroy** [devedroy/Contacts-App#1]
` E  FATAL EXCEPTION: main
                                                                                                    Process: com.devedroy.contactsapp, PID: 15295
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.devedroy.contactsapp/com.devedroy.contactsapp.SendMessageActivity}: java.lang.RuntimeException: Cannot find implementation for com.devedroy.contactsapp.data.MessageDatabase. MessageDatabase_Impl does not exist
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3771)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
                                                                                                    Caused by: java.lang.RuntimeException: Cannot find implementation for com.devedroy.contactsapp.data.MessageDatabase. MessageDatabase_Impl does not exist
                                                                                                    	at androidx.room.Room.getGeneratedImplementation(Room.kt:58)
                                                                                                    	at androidx.room.RoomDatabase$Builder.build(RoomDatabase.kt:1356)
                                                                                                    	at com.devedroy.contactsapp.SendMessageActivity.onCreate(SendMessageActivity.kt:48)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8163)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8130)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1330)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3744)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3938) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2291) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8319) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038) `

**Comment by nwaeme-olise** [comment]
I'm happy to take a look at this and try to come up with a fix.

**Comment by devedroy** [comment]
Sure, Please go ahead.
Thankyou.
